---
http_interactions:
- request:
    method: get
    uri: https://beta-engine.energytransitionmodel.com/api/v3/scenarios/648695
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - Faraday v2.7.2
      Authorization:
      - Bearer access_A5psxRtzdwLspScm
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
  response:
    status:
      code: 200
      message: OK
    headers:
      Server:
      - nginx/1.21.3
      Date:
      - Wed, 21 Dec 2022 10:16:50 GMT
      Content-Type:
      - application/json; charset=utf-8
      Transfer-Encoding:
      - chunked
      Connection:
      - keep-alive
      X-Frame-Options:
      - SAMEORIGIN
      X-Xss-Protection:
      - '0'
      X-Content-Type-Options:
      - nosniff
      X-Download-Options:
      - noopen
      X-Permitted-Cross-Domain-Policies:
      - none
      Referrer-Policy:
      - strict-origin-when-cross-origin
      Vary:
      - Accept, Origin
      Etag:
      - W/"278679e3bf98e20f1ae8e902e2fbbd60"
      Cache-Control:
      - max-age=0, private, must-revalidate
      X-Request-Id:
      - 5c97398b-9c63-482d-97dd-198e47a43a35
      X-Runtime:
      - '0.032197'
    body:
      encoding: UTF-8
      string: '{"id":648695,"created_at":"2017-03-13T19:22:35.000Z","updated_at":"2019-12-05T09:14:10.000Z","user_values":{},"end_year":2050,"keep_compatible":true,"private":false,"area_code":"nl","source":"ETM","balanced_values":{},"metadata":{"title":"ETM
        Test Scenario"},"start_year":2015,"template":null,"esdl_exportable":false,"url":"https://beta-engine.energytransitionmodel.com/api/v3/scenarios/648695"}'
  recorded_at: Wed, 21 Dec 2022 10:16:50 GMT
- request:
    method: post
    uri: https://beta-engine.energytransitionmodel.com/api/v3/scenarios
    body:
      encoding: UTF-8
      string: '{"scenario":{"source":"ETM","scenario_id":648695}}'
    headers:
      User-Agent:
      - Faraday v2.7.2
      Content-Type:
      - application/json
      Authorization:
      - Bearer access_A5psxRtzdwLspScm
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
  response:
    status:
      code: 200
      message: OK
    headers:
      Server:
      - nginx/1.21.3
      Date:
      - Wed, 21 Dec 2022 10:16:52 GMT
      Content-Type:
      - application/json; charset=utf-8
      Transfer-Encoding:
      - chunked
      Connection:
      - keep-alive
      X-Frame-Options:
      - SAMEORIGIN
      X-Xss-Protection:
      - '0'
      X-Content-Type-Options:
      - nosniff
      X-Download-Options:
      - noopen
      X-Permitted-Cross-Domain-Policies:
      - none
      Referrer-Policy:
      - strict-origin-when-cross-origin
      Vary:
      - Accept, Origin
      Etag:
      - W/"046dd1044608d768980449822744619a"
      Cache-Control:
      - max-age=0, private, must-revalidate
      X-Request-Id:
      - b9ba60d6-fc19-465f-bc07-e9df02ae1a01
      X-Runtime:
      - '1.725627'
    body:
      encoding: UTF-8
      string: '{"id":2179534,"created_at":"2022-12-21T10:16:52.000Z","updated_at":"2022-12-21T10:16:52.000Z","user_values":{},"end_year":2050,"keep_compatible":false,"private":false,"area_code":"nl","source":"ETM","balanced_values":{},"metadata":{},"start_year":2015,"template":648695,"esdl_exportable":false,"url":"https://beta-engine.energytransitionmodel.com/api/v3/scenarios/2179534"}'
  recorded_at: Wed, 21 Dec 2022 10:16:52 GMT
recorded_with: VCR 6.0.0
