---
http_interactions:
- request:
    method: post
    uri: https://beta-engine.energytransitionmodel.com/api/v3/scenarios
    body:
      encoding: UTF-8
      string: '{"scenario":{"source":"ETM","area_code":"nl","end_year":2050}}'
    headers:
      User-Agent:
      - Faraday v2.7.2
      Content-Type:
      - application/json
      Authorization:
      - Bearer access_PvY2W1q3RtKKWJrE
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
  response:
    status:
      code: 200
      message: OK
    headers:
      Server:
      - nginx/1.21.3
      Date:
      - Wed, 21 Dec 2022 10:16:38 GMT
      Content-Type:
      - application/json; charset=utf-8
      Transfer-Encoding:
      - chunked
      Connection:
      - keep-alive
      X-Frame-Options:
      - SAMEORIGIN
      X-Xss-Protection:
      - '0'
      X-Content-Type-Options:
      - nosniff
      X-Download-Options:
      - noopen
      X-Permitted-Cross-Domain-Policies:
      - none
      Referrer-Policy:
      - strict-origin-when-cross-origin
      Vary:
      - Accept, Origin
      Etag:
      - W/"172db4b1eddce4160afe8f34f018a063"
      Cache-Control:
      - max-age=0, private, must-revalidate
      X-Request-Id:
      - c2de7641-a53f-4e15-92ce-23922713eaa0
      X-Runtime:
      - '0.023795'
    body:
      encoding: UTF-8
      string: '{"id":2179527,"created_at":"2022-12-21T10:16:38.000Z","updated_at":"2022-12-21T10:16:38.000Z","user_values":{},"end_year":2050,"keep_compatible":false,"private":false,"area_code":"nl","source":"ETM","balanced_values":{},"metadata":{},"start_year":2015,"template":null,"esdl_exportable":false,"url":"https://beta-engine.energytransitionmodel.com/api/v3/scenarios/2179527"}'
  recorded_at: Wed, 21 Dec 2022 10:16:38 GMT
recorded_with: VCR 6.0.0
