---
- label: co2_emission
  color: "#49A5F8"
  order_by: 100
  group: steam_methane_reforming
  is_target_line: false
  gquery: co2_intensity_of_hydrogen_production_steam_methane_reformer
  output_element_key: co2_intensity_of_hydrogen_production
  key: co2_emission_steam_methane_reforming_co2_intensity_of_hydrogen_production

- label: co2_emission
  color: "#49A5F8"
  order_by: 200
  group: power_to_gas
  is_target_line: false
  gquery: co2_intensity_of_hydrogen_production_p2g_hourly_electricity_input
  output_element_key: co2_intensity_of_hydrogen_production
  key: co2_emission_power_to_gas_co2_intensity_of_hydrogen_production

- label: co2_emission
  color: "#49A5F8"
  order_by: 300
  group: biomass_gasification
  is_target_line: false
  gquery: co2_intensity_of_hydrogen_production_biomass_gasification
  output_element_key: co2_intensity_of_hydrogen_production
  key: co2_emission_biomass_gasification_co2_intensity_of_hydrogen_production

- label: co2_emission
  color: "#49A5F8"
  order_by: 150
  group: ammonia_reforming
  is_target_line: false
  gquery: co2_intensity_of_hydrogen_production_ammonia_reformer
  output_element_key: co2_intensity_of_hydrogen_production
  key: co2_intensity_of_hydrogen_production_ammonia_reformer_co2_intensity_of_hydrogen_production

- label: co2_emission
  color: "#49A5F8"
  order_by: 500
  group: import
  is_target_line: false
  gquery: co2_intensity_of_hydrogen_production_import
  output_element_key: co2_intensity_of_hydrogen_production
  key: co2_emission_import_co2_intensity_of_hydrogen_production
