---
- label: costs_building_and_installations_households
  color: "#002B42"
  order_by: 1
  group:
  show_at_first:
  is_target_line: false
  target_line_position:
  gquery: costs_building_and_installations_households
  is_1990: false
  dependent_on:
  output_element_key: costs_overview_detailed
  key: costs_building_and_installations_households_costs_overview_detailed
- label: costs_building_and_installations_buildings
  color: "#194054"
  order_by: 2
  group:
  show_at_first:
  is_target_line: false
  target_line_position:
  gquery: costs_building_and_installations_buildings
  is_1990: false
  dependent_on:
  output_element_key: costs_overview_detailed
  key: costs_building_and_installations_buildings_costs_overview_detailed
- label: costs_building_and_installations_agriculture
  color: "#325567"
  order_by: 3
  group:
  show_at_first:
  is_target_line: false
  target_line_position:
  gquery: costs_building_and_installations_agriculture
  is_1990: false
  dependent_on:
  output_element_key: costs_overview_detailed
  key: costs_building_and_installations_agriculture_costs_overview_detailed
- label: costs_building_and_installations_transport
  color: "#4c6a7a"
  order_by: 4
  group:
  show_at_first:
  is_target_line: false
  target_line_position:
  gquery: costs_building_and_installations_transport
  is_1990: false
  dependent_on:
  output_element_key: costs_overview_detailed
  key: costs_building_and_installations_transport_costs_overview
- label: costs_building_and_installations_industry
  color: "#667f8d"
  order_by: 5
  group:
  show_at_first:
  is_target_line: false
  target_line_position:
  gquery: costs_building_and_installations_industry
  is_1990: false
  dependent_on:
  output_element_key: costs_overview_detailed
  key: costs_building_and_installations_industry_costs_overview_detailed
- label: costs_carriers_biomass
  color: "#619ab7"
  order_by: 6
  group:
  show_at_first:
  is_target_line: false
  target_line_position:
  gquery: costs_carriers_biomass
  is_1990: false
  dependent_on:
  output_element_key: costs_overview_detailed
  key: costs_carriers_biomass_costs_overview_detailed
- label: costs_carriers_coal_and_products
  color: "#70a4be"
  order_by: 7
  group:
  show_at_first:
  is_target_line: false
  target_line_position:
  gquery: costs_carriers_coal_and_products
  is_1990: false
  dependent_on:
  output_element_key: costs_overview_detailed
  key: costs_carriers_coal_and_products_costs_overview_detailed
- label: costs_carriers_electricity
  color: "#80aec5"
  order_by: 8
  group:
  show_at_first:
  is_target_line: false
  target_line_position:
  gquery: costs_carriers_electricity
  is_1990: false
  dependent_on:
  output_element_key: costs_overview_detailed
  key: costs_carriers_electricity_costs_overview_detailed
- label: costs_carriers_heat
  color: "#90b8cc"
  order_by: 9
  group:
  show_at_first:
  is_target_line: false
  target_line_position:
  gquery: costs_carriers_heat
  is_1990: false
  dependent_on:
  output_element_key: costs_overview_detailed
  key: costs_carriers_heat_costs_overview_detailed
- label: costs_carriers_hydrogen
  color: "#a0c2d3"
  order_by: 10
  group:
  show_at_first:
  is_target_line: false
  target_line_position:
  gquery: costs_carriers_hydrogen
  is_1990: false
  dependent_on:
  output_element_key: costs_overview_detailed
  key: costs_carriers_hydrogen_costs_overview_detailed
- label: costs_carriers_natural_gas
  color: "#b0ccdb"
  order_by: 11
  group:
  show_at_first:
  is_target_line: false
  target_line_position:
  gquery: costs_carriers_natural_gas
  is_1990: false
  dependent_on:
  output_element_key: costs_overview_detailed
  key: costs_carriers_natural_gas_costs_overview_detailed
- label: costs_carriers_oil_and_products
  color: "#bfd6e2"
  order_by: 12
  group:
  show_at_first:
  is_target_line: false
  target_line_position:
  gquery: costs_carriers_oil_and_products
  is_1990: false
  dependent_on:
  output_element_key: costs_overview_detailed
  key: costs_carriers_oil_and_products_costs_overview_detailed
- label: costs_carriers_uranium
  color: "#cfe0e9"
  order_by: 13
  group:
  show_at_first:
  is_target_line: false
  target_line_position:
  gquery: costs_carriers_uranium
  is_1990: false
  dependent_on:
  output_element_key: costs_overview_detailed
  key: costs_carriers_uranium_costs_overview_detailed
- label: costs_carriers_waste
  color: "#dfeaf0"
  order_by: 14
  group:
  show_at_first:
  is_target_line: false
  target_line_position:
  gquery: costs_carriers_waste
  is_1990: false
  dependent_on:
  output_element_key: costs_overview_detailed
  key: costs_carriers_waste_costs_overview_detailed
- label: costs_production_biomass
  color: "#C5D75F"
  order_by: 15
  group:
  show_at_first:
  is_target_line: false
  target_line_position:
  gquery: costs_production_biomass
  is_1990: false
  dependent_on:
  output_element_key: costs_overview_detailed
  key: costs_production_biomass_costs_overview_detailed
- label: costs_production_chp_plants
  color: "#cadb6f"
  order_by: 16
  group:
  show_at_first:
  is_target_line: false
  target_line_position:
  gquery: costs_production_chp_plants
  is_1990: false
  dependent_on:
  output_element_key: costs_overview_detailed
  key: costs_production_chp_plants_overview_detailed
- label: costs_production_dedicated_hydrogen_production
  color: "#D0DF7E"
  order_by: 17
  group:
  show_at_first:
  is_target_line: false
  target_line_position:
  gquery: costs_production_dedicated_hydrogen_production
  is_1990: false
  dependent_on:
  output_element_key: costs_overview_detailed
  key: costs_production_dedicated_hydrogen_production_costs_overview_detailed
- label: costs_production_heat_plants
  color: "#D6E38F"
  order_by: 18
  group:
  show_at_first:
  is_target_line: false
  target_line_position:
  gquery: costs_production_heat_plants
  is_1990: false
  dependent_on:
  output_element_key: costs_overview_detailed
  key: costs_production_heat_plants_costs_overview_detailed
- label: costs_production_other
  color: "#DCE79F"
  order_by: 19
  group:
  show_at_first:
  is_target_line: false
  target_line_position:
  gquery: costs_production_other
  is_1990: false
  dependent_on:
  output_element_key: costs_overview_detailed
  key: costs_production_other_costs_overview_detailed
- label: costs_production_power_plants
  color: "#E2EBAF"
  order_by: 20
  group:
  show_at_first:
  is_target_line: false
  target_line_position:
  gquery: costs_production_power_plants
  is_1990: false
  dependent_on:
  output_element_key: costs_overview_detailed
  key: costs_production_power_plants_costs_overview_detailed
- label: costs_storage_and_conversion_p2p
  color: "#CAB39E"
  order_by: 21
  group:
  show_at_first:
  is_target_line: false
  target_line_position:
  gquery: costs_storage_and_conversion_p2p
  is_1990: false
  dependent_on:
  output_element_key: costs_overview_detailed
  key: costs_storage_and_conversion_p2p_costs_overview_detailed
- label: costs_storage_and_conversion_p2g
  color: "#cfbaa7"
  order_by: 22
  group:
  show_at_first:
  is_target_line: false
  target_line_position:
  gquery: costs_storage_and_conversion_p2g
  is_1990: false
  dependent_on:
  output_element_key: costs_overview_detailed
  key: costs_storage_and_conversion_p2g_costs_overview_detailed
- label: costs_storage_and_conversion_p2h
  color: "#d4c2b1"
  order_by: 23
  group:
  show_at_first:
  is_target_line: false
  target_line_position:
  gquery: costs_storage_and_conversion_p2h
  is_1990: false
  dependent_on:
  output_element_key: costs_overview_detailed
  key: costs_storage_and_conversion_p2h_costs_overview_detailed
- label: costs_storage_and_conversion_storage
  color: "#d9c9bb"
  order_by: 24
  group:
  show_at_first:
  is_target_line: false
  target_line_position:
  gquery: costs_storage_and_conversion_storage
  is_1990: false
  dependent_on:
  output_element_key: costs_overview_detailed
  key: costs_storage_and_conversion_storage_costs_overview_detailed
- label: costs_infrastructure_electricity
  color: "#702283"
  order_by: 25
  group:
  show_at_first:
  is_target_line: false
  target_line_position:
  gquery: costs_infrastructure_electricity
  is_1990: false
  dependent_on:
  output_element_key: costs_overview_detailed
  key: costs_infrastructure_electricity_costs_overview_detailed
- label: costs_infrastructure_heat
  color: "#7e388f"
  order_by: 26
  group:
  show_at_first:
  is_target_line: false
  target_line_position:
  gquery: costs_infrastructure_heat
  is_1990: false
  dependent_on:
  output_element_key: costs_overview_detailed
  key: costs_infrastructure_heat_costs_overview_detailed
- label: costs_infrastructure_hydrogen
  color: "#8c4e9b"
  order_by: 27
  group:
  show_at_first:
  is_target_line: false
  target_line_position:
  gquery: costs_infrastructure_hydrogen
  is_1990: false
  dependent_on:
  output_element_key: costs_overview_detailed
  key: costs_infrastructure_hydrogen_costs_overview_detailed
- label: costs_infrastructure_network_gas
  color: "#9a64a8"
  order_by: 28
  group:
  show_at_first:
  is_target_line: false
  target_line_position:
  gquery: costs_infrastructure_network_gas
  is_1990: false
  dependent_on:
  output_element_key: costs_overview_detailed
  key: costs_infrastructure_network_gas_costs_overview_detailed
- label: costs_co2
  color: "#FCC43D"
  order_by: 29
  group:
  show_at_first:
  is_target_line: false
  target_line_position:
  gquery: costs_co2
  is_1990: false
  dependent_on:
  output_element_key: costs_overview_detailed
  key: costs_co2_costs_overview_detailed
