---
- label: costs_building_and_installations_households
  color: "#416B86"
  order_by: 1
  group: 
  show_at_first:
  is_target_line: false
  target_line_position:
  gquery: costs_building_and_installations_households
  is_1990: false 
  dependent_on:
  output_element_key: costs_overview_detailed
  key: costs_building_and_installations_households_costs_overview_detailed
- label: costs_building_and_installations_buildings
  color: "#74B9FF"
  order_by: 2
  group: 
  show_at_first:
  is_target_line: false
  target_line_position:
  gquery: costs_building_and_installations_buildings
  is_1990: false 
  dependent_on:
  output_element_key: costs_overview_detailed
  key: costs_building_and_installations_buildings_costs_overview_detailed
- label: costs_building_and_installations_agriculture
  color: "#CC0000"
  order_by: 3
  group: 
  show_at_first:
  is_target_line: false
  target_line_position:
  gquery: costs_building_and_installations_agriculture
  is_1990: false 
  dependent_on:
  output_element_key: costs_overview_detailed
  key: costs_building_and_installations_agriculture_costs_overview_detailed
- label: costs_building_and_installations_transport
  color: "#FF8C8C"
  order_by: 4
  group: 
  show_at_first:
  is_target_line: false
  target_line_position:
  gquery: costs_building_and_installations_transport
  is_1990: false
  dependent_on:
  output_element_key: costs_overview_detailed
  key: costs_building_and_installations_transport_costs_overview
- label: costs_building_and_installations_industry
  color: "#b71540"
  order_by: 5
  group: 
  show_at_first:
  is_target_line: false
  target_line_position:
  gquery: costs_building_and_installations_industry
  is_1990: false
  dependent_on:
  output_element_key: costs_overview_detailed
  key: costs_building_and_installations_industry_costs_overview_detailed
- label: costs_storage_and_conversion_p2p
  color: "#786FA6"
  order_by: 6
  group: 
  show_at_first:
  is_target_line: false
  target_line_position:
  gquery: costs_storage_and_conversion_p2p
  is_1990: false
  dependent_on:
  output_element_key: costs_overview_detailed
  key: costs_storage_and_conversion_p2p_costs_overview_detailed
- label: costs_storage_and_conversion_p2g
  color: "#A4B0BE"
  order_by: 7
  group: 
  show_at_first:
  is_target_line: false
  target_line_position:
  gquery: costs_storage_and_conversion_p2g
  is_1990: false
  dependent_on:
  output_element_key: costs_overview_detailed
  key: costs_storage_and_conversion_p2g_costs_overview_detailed
- label: costs_storage_and_conversion_p2h
  color: "#63A1C9"
  order_by: 8
  group: 
  show_at_first:
  is_target_line: false
  target_line_position:
  gquery: costs_storage_and_conversion_p2h
  is_1990: false
  dependent_on:
  output_element_key: costs_overview_detailed
  key: costs_storage_and_conversion_p2h_costs_overview_detailed
- label: costs_production_biomass
  color: "#FFA502"
  order_by: 9
  group: 
  show_at_first:
  is_target_line: false
  target_line_position:
  gquery: costs_production_biomass
  is_1990: false
  dependent_on:
  output_element_key: costs_overview_detailed
  key: costs_production_biomass_costs_overview_detailed
- label: costs_production_chp_plants
  color: "#A2D679"
  order_by: 10
  group: 
  show_at_first:
  is_target_line: false
  target_line_position:
  gquery: costs_production_chp_plants
  is_1990: false
  dependent_on:
  output_element_key: costs_overview_detailed
  key: costs_production_chp_plants_overview_detailed
- label: costs_production_dedicated_hydrogen_production
  color: "#394C19"
  order_by: 11
  group: 
  show_at_first:
  is_target_line: false
  target_line_position:
  gquery: costs_production_dedicated_hydrogen_production
  is_1990: false
  dependent_on:
  output_element_key: costs_overview_detailed
  key: costs_production_dedicated_hydrogen_production_costs_overview_detailed
- label: costs_production_heat_plants
  color: "#485460"
  order_by: 12
  group: 
  show_at_first:
  is_target_line: false
  target_line_position:
  gquery: costs_production_heat_plants
  is_1990: false
  dependent_on:
  output_element_key: costs_overview_detailed
  key: costs_production_heat_plants_costs_overview_detailed

- label: costs_production_other
  color: "#228B22"
  order_by: 13
  group: 
  show_at_first:
  is_target_line: false
  target_line_position:
  gquery: costs_production_other
  is_1990: false
  dependent_on:
  output_element_key: costs_overview_detailed
  key: costs_production_other_costs_overview_detailed
- label: costs_production_power_plants
  color: "#666666"
  order_by: 14
  group: 
  show_at_first:
  is_target_line: false
  target_line_position:
  gquery: costs_production_power_plants
  is_1990: false costs_production
  dependent_on:
  output_element_key: costs_overview_detailed
  key: costs_production_power_plants_costs_overview_detailed
- label: costs_carriers_biomass
  color: "#E69567"
  order_by: 15
  group: 
  show_at_first:
  is_target_line: false
  target_line_position:
  gquery: costs_carriers_biomass
  is_1990: false
  dependent_on:
  output_element_key: costs_overview_detailed
  key: costs_carriers_biomass_costs_overview_detailed
- label: costs_carriers_coal_and_products
  color: "#A9A9A9"
  order_by: 16
  group: 
  show_at_first:
  is_target_line: false
  target_line_position:
  gquery: costs_carriers_coal_and_products
  is_1990: false
  dependent_on:
  output_element_key: costs_overview_detailed
  key: costs_carriers_coal_and_products_costs_overview_detailed
- label: costs_carriers_electricity
  color: "#5D7929"
  order_by: 17
  group: 
  show_at_first:
  is_target_line: false
  target_line_position:
  gquery: costs_carriers_electricity
  is_1990: false
  dependent_on:
  output_element_key: costs_overview_detailed
  key: costs_carriers_electricity_costs_overview_detailed
- label: costs_carriers_heat
  color: "#4169E1"
  order_by: 18
  group: 
  show_at_first:
  is_target_line: false
  target_line_position:
  gquery: costs_carriers_heat
  is_1990: false
  dependent_on:
  output_element_key: costs_overview_detailed
  key: costs_carriers_heat_costs_overview_detailed
- label: costs_carriers_hydrogen
  color: "#333333"
  order_by: 19
  group: 
  show_at_first:
  is_target_line: false
  target_line_position:
  gquery: costs_carriers_hydrogen
  is_1990: false
  dependent_on:
  output_element_key: costs_overview_detailed
  key: costs_carriers_hydrogen_costs_overview_detailed
- label: costs_carriers_natural_gas
  color: "#00008B"
  order_by: 20
  group: 
  show_at_first:
  is_target_line: false
  target_line_position:
  gquery: costs_carriers_natural_gas
  is_1990: false
  dependent_on:
  output_element_key: costs_overview_detailed
  key: costs_carriers_natural_gas_costs_overview_detailed
- label: costs_carriers_oil_and_products
  color: "#854321"
  order_by: 21
  group: 
  show_at_first:
  is_target_line: false
  target_line_position:
  gquery: costs_carriers_oil_and_products
  is_1990: false
  dependent_on:
  output_element_key: costs_overview_detailed
  key: costs_carriers_oil_and_products_costs_overview_detailed
- label: costs_carriers_uranium
  color: "#ADDE4C"
  order_by: 22
  group: 
  show_at_first:
  is_target_line: false
  target_line_position:
  gquery: costs_carriers_uranium
  is_1990: false
  dependent_on:
  output_element_key: costs_overview_detailed
  key: costs_carriers_uranium_costs_overview_detailed
- label: costs_carriers_waste
  color: "#B3CF7B"
  order_by: 23
  group: 
  show_at_first:
  is_target_line: false
  target_line_position:
  gquery: costs_carriers_waste
  is_1990: false
  dependent_on:
  output_element_key: costs_overview_detailed
  key: costs_carriers_waste_costs_overview_detailed
- label: costs_infrastructure_electricity
  color: "#009432"
  order_by: 24
  group: 
  show_at_first:
  is_target_line: false
  target_line_position:
  gquery: costs_infrastructure_electricity
  is_1990: false
  dependent_on:
  output_element_key: costs_overview_detailed
  key: costs_infrastructure_electricity_costs_overview_detailed
- label: costs_infrastructure_heat
  color: "#C6C2DA"
  order_by: 25
  group: 
  show_at_first:
  is_target_line: false
  target_line_position:
  gquery: costs_infrastructure_heat
  is_1990: false
  dependent_on:
  output_element_key: costs_overview_detailed
  key: costs_infrastructure_heat_costs_overview_detailed
- label: costs_infrastructure_hydrogen
  color: "#87CEEB"
  order_by: 26
  group: 
  show_at_first:
  is_target_line: false
  target_line_position:
  gquery: costs_infrastructure_hydrogen
  is_1990: false
  dependent_on:
  output_element_key: costs_overview_detailed
  key: costs_infrastructure_hydrogen_costs_overview_detailed
- label: costs_infrastructure_network_gas
  color: "#C6C2DA"
  order_by: 27
  group: 
  show_at_first:
  is_target_line: false
  target_line_position:
  gquery: costs_infrastructure_network_gas
  is_1990: false
  dependent_on:
  output_element_key: costs_overview_detailed
  key: costs_infrastructure_network_gas_costs_overview_detailed
- label: costs_co2
  color: "#87CEEB"
  order_by: 28
  group: 
  show_at_first:
  is_target_line: false
  target_line_position:
  gquery: costs_co2
  is_1990: false
  dependent_on:
  output_element_key: costs_overview_detailed
  key: costs_co2_costs_overview_detailed
