---
- color: "#4169E1"
  dependent_on:
  gquery: electricity_imbalance_inflexible_curve
  key: electricity_imbalance_inflexible_curve_flexiblity_hourly_carriers_inflexible_imbalance
  label: electricity
  order_by: 1
  output_element_key: flexibility_hourly_carriers_inflexible_imbalance

- color: "#B22222"
  dependent_on:
  gquery: heat_network_imbalance_inflexible_curve
  key: heat_network_imbalance_inflexible_curve_flexiblity_hourly_carriers_inflexible_imbalance
  label: heat
  order_by: 2
  output_element_key: flexibility_hourly_carriers_inflexible_imbalance

- color: "#CCCCCC"
  dependent_on:
  gquery: network_gas_imbalance_inflexible_curve
  key: network_gas_imbalance_inflexible_curve_flexiblity_hourly_carriers_inflexible_imbalance
  label: gas
  order_by: 30
  output_element_key: flexibility_hourly_carriers_inflexible_imbalance

- color: "#999999"
  dependent_on:
  gquery: network_gas_imbalance_inflexible_smoothed_curve
  key: network_gas_imbalance_inflexible_smoothed_curve_flexiblity_hourly_carriers_inflexible_imbalance
  label: gas_smoothed
  order_by: 31
  output_element_key: flexibility_hourly_carriers_inflexible_imbalance

- color: "#87CEEB"
  dependent_on:
  gquery: hydrogen_imbalance_inflexible_curve
  key: hydrogen_imbalance_inflexible_curve_flexiblity_hourly_carriers_inflexible_imbalance
  label: hydrogen
  order_by: 40
  output_element_key: flexibility_hourly_carriers_inflexible_imbalance

- color: "#69a2b8"
  dependent_on:
  gquery: hydrogen_imbalance_inflexible_smoothed_curve
  key: hydrogen_imbalance_inflexible_smoothed_curve_flexiblity_hourly_carriers_inflexible_imbalance
  label: hydrogen_smoothed
  order_by: 41
  output_element_key: flexibility_hourly_carriers_inflexible_imbalance
