---
- label: trucks_demand_for_diesel
  color: "#854321"
  order_by: 100
  group: ''
  show_at_first: false
  is_target_line: false
  target_line_position:
  gquery: final_demand_of_diesel_in_truck_road_freight_transport_energetic
  is_1990: false
  dependent_on:
  output_element_key: use_of_final_demand_in_freight_road_transport
  key: trucks_diesel_use_of_final_demand_in_freight_road_transport
- label: vans_demand_for_diesel
  color: "#82002b"
  order_by: 105
  group: ''
  show_at_first: false
  is_target_line: false
  target_line_position:
  gquery: final_demand_of_diesel_in_van_road_freight_transport_energetic
  is_1990: false
  dependent_on:
  output_element_key: use_of_final_demand_in_freight_road_transport
  key: vans_diesel_use_of_final_demand_in_freight_road_transport

- label: trucks_demand_for_gasoline
  color: "#8B0000"
  order_by: 110
  group: ''
  show_at_first: false
  is_target_line: false
  target_line_position:
  gquery: final_demand_of_gasoline_in_truck_road_freight_transport_energetic
  is_1990: false
  dependent_on:
  output_element_key: use_of_final_demand_in_freight_road_transport
  key: trucks_gasoline_use_of_final_demand_in_freight_road_transport
- label: vans_demand_for_gasoline
  color: "#E84118"
  order_by: 115
  group: ''
  show_at_first: false
  is_target_line: false
  target_line_position:
  gquery: final_demand_of_gasoline_in_van_road_freight_transport_energetic
  is_1990: false
  dependent_on:
  output_element_key: use_of_final_demand_in_freight_road_transport
  key: vans_gasoline_use_of_final_demand_in_freight_road_transport

- label: trucks_demand_for_compressed_natural_gas
  color: "#32a4a8"
  order_by: 120
  group: ''
  show_at_first: false
  is_target_line: false
  target_line_position:
  gquery: final_demand_of_compressed_natural_gas_in_truck_road_freight_transport_energetic
  is_1990: false
  dependent_on:
  output_element_key: use_of_final_demand_in_freight_road_transport
  key: trucks_compressed_natural_gas_use_of_final_demand_in_freight_road_transport
- label: vans_demand_for_compressed_natural_gas
  color: "#006266"
  order_by: 125
  group: ''
  show_at_first: false
  is_target_line: false
  target_line_position:
  gquery: final_demand_of_compressed_natural_gas_in_van_road_freight_transport_energetic
  is_1990: false
  dependent_on:
  output_element_key: use_of_final_demand_in_freight_road_transport
  key: vans_compressed_natural_gas_use_of_final_demand_in_freight_road_transport

- label: trucks_demand_for_lng
  color: "#696969"
  order_by: 130
  group: ''
  show_at_first: false
  is_target_line: false
  target_line_position:
  gquery: final_demand_of_lng_in_truck_road_freight_transport_energetic
  is_1990: false
  dependent_on:
  output_element_key: use_of_final_demand_in_freight_road_transport
  key: trucks_lng_use_of_final_demand_in_freight_road_transport

- label: vans_demand_for_lpg
  color: "#7040c2"
  order_by: 135
  group: ''
  show_at_first: false
  is_target_line: false
  target_line_position:
  gquery: final_demand_of_lpg_in_van_road_freight_transport_energetic
  is_1990: false
  dependent_on:
  output_element_key: use_of_final_demand_in_freight_road_transport
  key: vans_lpg_use_of_final_demand_in_freight_road_transport

- label: trucks_demand_for_biodiesel
  color: "#5D7929"
  order_by: 200
  group: ''
  show_at_first: false
  is_target_line: false
  target_line_position:
  gquery: final_demand_of_biodiesel_in_truck_road_freight_transport_energetic
  is_1990: false
  dependent_on:
  output_element_key: use_of_final_demand_in_freight_road_transport
  key: trucks_biodiesel_use_of_final_demand_in_freight_road_transport
- label: vans_demand_for_biodiesel
  color: "#a6db44"
  order_by: 205
  group: ''
  show_at_first: false
  is_target_line: false
  target_line_position:
  gquery: final_demand_of_biodiesel_in_van_road_freight_transport_energetic
  is_1990: false
  dependent_on:
  output_element_key: use_of_final_demand_in_freight_road_transport
  key: vans_biodiesel_use_of_final_demand_in_freight_road_transport

- label: trucks_demand_for_bio_ethanol
  color: "#394C19"
  order_by: 210
  group: ''
  show_at_first: false
  is_target_line: false
  target_line_position:
  gquery: final_demand_of_bio_ethanol_in_truck_road_freight_transport_energetic
  is_1990: false
  dependent_on:
  output_element_key: use_of_final_demand_in_freight_road_transport
  key: trucks_bio_ethanol_use_of_final_demand_in_freight_road_transport
- label: vans_demand_for_bio_ethanol
  color: "#538500"
  order_by: 215
  group: ''
  show_at_first: false
  is_target_line: false
  target_line_position:
  gquery: final_demand_of_bio_ethanol_in_van_road_freight_transport_energetic
  is_1990: false
  dependent_on:
  output_element_key: use_of_final_demand_in_freight_road_transport
  key: vans_bio_ethanol_use_of_final_demand_in_freight_road_transport

- label: trucks_demand_for_bio_lng
  color: "#006400"
  order_by: 220
  group: ''
  show_at_first: false
  is_target_line: false
  target_line_position:
  gquery: final_demand_of_bio_lng_in_truck_road_freight_transport_energetic
  is_1990: false
  dependent_on:
  output_element_key: use_of_final_demand_in_freight_road_transport
  key: trucks_bio_lng_use_of_final_demand_in_freight_road_transport

- label: trucks_demand_for_electricity
  color: "#4169E1"
  order_by: 300
  group: ''
  show_at_first: false
  is_target_line: false
  target_line_position:
  gquery: final_demand_of_electricity_in_truck_road_freight_transport_energetic
  is_1990: false
  dependent_on:
  output_element_key: use_of_final_demand_in_freight_road_transport
  key: trucks_electricity_use_of_final_demand_in_freight_road_transport
- label: vans_demand_for_electricity
  color: "#00008B"
  order_by: 305
  group: ''
  show_at_first: false
  is_target_line: false
  target_line_position:
  gquery: final_demand_of_electricity_in_van_road_freight_transport_energetic
  is_1990: false
  dependent_on:
  output_element_key: use_of_final_demand_in_freight_road_transport
  key: vans_electricity_use_of_final_demand_in_freight_road_transport

- label: trucks_demand_for_hydrogen
  color: "#87CEEB"
  order_by: 300
  group: ''
  show_at_first: false
  is_target_line: false
  target_line_position:
  gquery: final_demand_of_hydrogen_in_truck_road_freight_transport_energetic
  is_1990: false
  dependent_on:
  output_element_key: use_of_final_demand_in_freight_road_transport
  key: trucks_hydrogen_use_of_final_demand_in_freight_road_transport
- label: vans_demand_for_hydrogen
  color: "#08beff"
  order_by: 305
  group: ''
  show_at_first: false
  is_target_line: false
  target_line_position:
  gquery: final_demand_of_hydrogen_in_van_road_freight_transport_energetic
  is_1990: false
  dependent_on:
  output_element_key: use_of_final_demand_in_freight_road_transport
  key: vans_hydrogen_use_of_final_demand_in_freight_road_transport
