---
- label: diesel
  color: "#854321"
  order_by: 105
  group: ''
  show_at_first: false
  is_target_line: false
  target_line_position:
  gquery: final_demand_of_diesel_in_van_road_freight_transport_energetic
  is_1990: false
  dependent_on:
  output_element_key: use_of_final_demand_in_freight_van_transport
  key: diesel_use_of_final_demand_in_freight_van_transport
- label: gasoline
  color: "#8B0000"
  order_by: 115
  group: ''
  show_at_first: false
  is_target_line: false
  target_line_position:
  gquery: final_demand_of_gasoline_in_van_road_freight_transport_energetic
  is_1990: false
  dependent_on:
  output_element_key: use_of_final_demand_in_freight_van_transport
  key: gasoline_use_of_final_demand_in_freight_van_transport
- label: compressed_natural_gas
  color: "#32a4a8"
  order_by: 125
  group: ''
  show_at_first: false
  is_target_line: false
  target_line_position:
  gquery: final_demand_of_compressed_natural_gas_in_van_road_freight_transport_energetic
  is_1990: false
  dependent_on:
  output_element_key: use_of_final_demand_in_freight_van_transport
  key: compressed_natural_gas_use_of_final_demand_in_freight_van_transport
- label: lpg
  color: "#7040c2"
  order_by: 135
  group: ''
  show_at_first: false
  is_target_line: false
  target_line_position:
  gquery: final_demand_of_lpg_in_van_road_freight_transport_energetic
  is_1990: false
  dependent_on:
  output_element_key: use_of_final_demand_in_freight_van_transport
  key: lpg_use_of_final_demand_in_freight_van_transport
- label: biodiesel
  color: "#5D7929"
  order_by: 205
  group: ''
  show_at_first: false
  is_target_line: false
  target_line_position:
  gquery: final_demand_of_biodiesel_in_van_road_freight_transport_energetic
  is_1990: false
  dependent_on:
  output_element_key: use_of_final_demand_in_freight_van_transport
  key: biodiesel_use_of_final_demand_in_freight_van_transport
- label: bio_ethanol
  color: "#394C19"
  order_by: 215
  group: ''
  show_at_first: false
  is_target_line: false
  target_line_position:
  gquery: final_demand_of_bio_ethanol_in_van_road_freight_transport_energetic
  is_1990: false
  dependent_on:
  output_element_key: use_of_final_demand_in_freight_van_transport
  key: bio_ethanol_use_of_final_demand_in_freight_van_transport
- label: electricity
  color: "#4169E1"
  order_by: 305
  group: ''
  show_at_first: false
  is_target_line: false
  target_line_position:
  gquery: final_demand_of_electricity_in_van_road_freight_transport_energetic
  is_1990: false
  dependent_on:
  output_element_key: use_of_final_demand_in_freight_van_transport
  key: electricity_use_of_final_demand_in_freight_van_transport
- label: hydrogen
  color: "#87CEEB"
  order_by: 310
  group: ''
  show_at_first: false
  is_target_line: false
  target_line_position:
  gquery: final_demand_of_hydrogen_in_van_road_freight_transport_energetic
  is_1990: false
  dependent_on:
  output_element_key: use_of_final_demand_in_freight_van_transport
  key: hydrogen_use_of_final_demand_in_freight_van_transport
