---
- label: diesel
  color: "#854321"
  order_by: 100
  group: ''
  show_at_first: false
  is_target_line: false
  target_line_position:
  gquery: final_demand_of_diesel_in_train_freight_transport_energetic
  is_1990: false
  dependent_on:
  output_element_key: use_of_final_demand_in_freight_train_transport
  key: diesel_use_of_final_demand_in_freight_train_transport
- label: biodiesel
  color: "#5D7929"
  order_by: 105
  group: ''
  show_at_first: false
  is_target_line: false
  target_line_position:
  gquery: final_demand_of_biodiesel_in_train_freight_transport_energetic
  is_1990: false
  dependent_on:
  output_element_key: use_of_final_demand_in_freight_train_transport
  key: biodiesel_use_of_final_demand_in_freight_train_transport
- label: hydrogen
  color: "#87CEEB"
  order_by: 110
  group: ''
  show_at_first: false
  is_target_line: false
  target_line_position:
  gquery: final_demand_of_hydrogen_in_train_freight_transport_energetic
  is_1990: false
  dependent_on:
  output_element_key: use_of_final_demand_in_freight_train_transport
  key: hydrogen_use_of_final_demand_in_freight_train_transport
- label: electricity
  color: "#4169E1"
  order_by: 115
  group: ''
  show_at_first: false
  is_target_line: false
  target_line_position:
  gquery: final_demand_of_electricity_in_train_freight_transport_energetic
  is_1990: false
  dependent_on:
  output_element_key: use_of_final_demand_in_freight_train_transport
  key: electricity_use_of_final_demand_in_freight_train_transport

