---
- image: tractor_and_greenhouse.gif
  general_sub_header: "%/year"
  key: demand_agriculture_demand_growth
  position: 1
  sidebar_item_key: agriculture
  alt_output_element_key: use_of_final_demand_in_agriculture
  output_element_key: use_of_final_demand_in_agriculture
- image: tractor_and_greenhouse.gif
  group_sub_header: of_heat_demand
  key: demand_agriculture_heat
  position: 2
  sidebar_item_key: agriculture
  alt_output_element_key: source_of_heat_in_agriculture
  output_element_key: source_of_heat_in_agriculture
- group_sub_header: electricity_output
  key: supply_agriculture_local_heat
  position: 13
  sidebar_item_key: agriculture
  output_element_key: agriculture_local_heat_mekko
