---
- key: costs_hydrogen_production
  position: 1
  sidebar_item_key: costs_hydrogen
  output_element_key: hydrogen_cost_capacity
- key: costs_hydrogen_import
  position: 2
  sidebar_item_key: costs_hydrogen
  output_element_key: hydrogen_cost_capacity
- key: costs_hydrogen_storage
  position: 3
  sidebar_item_key: costs_hydrogen
  output_element_key: costs_overview_detailed
- key: costs_hydrogen_transport
  position: 4
  sidebar_item_key: costs_hydrogen
  output_element_key: costs_overview_detailed
- key: costs_ammonia_import
  position: 100
  sidebar_item_key: costs_hydrogen
  output_element_key: costs_overview_detailed
