---
- key: flexibility_electricity_import_export_interconnectivity_intro
  position: 1
  sidebar_item_key: electricity_import_export
  alt_output_element_key: merit_order_price_curve
  output_element_key: sankey_electrical_interconnection
- key: flexibility_electricity_import_export_interconnectivity
  position: 2
  sidebar_item_key: electricity_import_export
  alt_output_element_key: merit_order_price_curve
  output_element_key: merit_order_price_curve
- key: flexibility_electricity_import_export_interconnectivity_2
  position: 3
  sidebar_item_key: electricity_import_export
  alt_output_element_key: merit_order_price_curve
  output_element_key: merit_order_price_curve
- key: flexibility_electricity_import_export_interconnectivity_3
  position: 4
  sidebar_item_key: electricity_import_export
  alt_output_element_key: merit_order_price_curve
  output_element_key: merit_order_price_curve
- key: flexibility_electricity_import_export_interconnectivity_4
  position: 5
  sidebar_item_key: electricity_import_export
  alt_output_element_key: merit_order_price_curve
  output_element_key: merit_order_price_curve
- key: flexibility_electricity_import_export_interconnectivity_5
  position: 6
  sidebar_item_key: electricity_import_export
  alt_output_element_key: merit_order_price_curve
  output_element_key: merit_order_price_curve
- key: flexibility_electricity_import_export_interconnectivity_6
  position: 7
  sidebar_item_key: electricity_import_export
  alt_output_element_key: merit_order_price_curve
  output_element_key: merit_order_price_curve
- key: flexibility_electricity_import_export_interconnectivity_7
  position: 8
  sidebar_item_key: electricity_import_export
  alt_output_element_key: merit_order_price_curve
  output_element_key: merit_order_price_curve
- key: flexibility_electricity_import_export_interconnectivity_8
  position: 9
  sidebar_item_key: electricity_import_export
  alt_output_element_key: merit_order_price_curve
  output_element_key: merit_order_price_curve
- key: flexibility_electricity_import_export_interconnectivity_9
  position: 10
  sidebar_item_key: electricity_import_export
  alt_output_element_key: merit_order_price_curve
  output_element_key: merit_order_price_curve
- key: flexibility_electricity_import_export_interconnectivity_10
  position: 11
  sidebar_item_key: electricity_import_export
  alt_output_element_key: merit_order_price_curve
  output_element_key: merit_order_price_curve
- key: flexibility_electricity_import_export_interconnectivity_11
  position: 12
  sidebar_item_key: electricity_import_export
  alt_output_element_key: merit_order_price_curve
  output_element_key: merit_order_price_curve
- key: flexibility_electricity_import_export_interconnectivity_12
  position: 13
  sidebar_item_key: electricity_import_export
  alt_output_element_key: merit_order_price_curve
  output_element_key: merit_order_price_curve
