---
- general_sub_header: input_capacity
  key: supply_hydrogen_production
  position: 100
  sidebar_item_key: hydrogen
  alt_output_element_key: hydrogen_production
  output_element_key: mekko_of_hydrogen_network
- key: supply_hydrogen_demand
  position: 110
  sidebar_item_key: hydrogen
  output_element_key: hydrogen_demand
- general_sub_header: share
  key: supply_hydrogen_transport
  position: 120
  sidebar_item_key: hydrogen
  output_element_key: mekko_of_hydrogen_network
- key: supply_hydrogen_storage
  position: 130
  sidebar_item_key: hydrogen
  output_element_key: hydrogen_storage
- key: supply_ammonia_production
  position: 140
  sidebar_item_key: hydrogen
  output_element_key: mekko_of_ammonia_demand_supply
- key: supply_hydrogen_co2_import
  position: 200
  sidebar_item_key: hydrogen
  output_element_key: co2_intensity_of_hydrogen_production
- key: supply_ammonia_co2_import
  position: 210
  sidebar_item_key: hydrogen
  output_element_key: co2_intensity_of_hydrogen_production
