---
- key: industry_aluminium_production
  step_value: 0.1
  unit: "%"
  position: 1
  slide_key: demand_industry_aluminium
- key: industry_aluminium_electrolysis_bat_electricity_share
  share_group: aluminium_production
  step_value: 0.1
  unit: "%"
  interface_group: production_route
  position: 2
  slide_key: demand_industry_aluminium
- key: industry_aluminium_smeltoven_electricity_share
  share_group: aluminium_production
  step_value: 0.1
  unit: "%"
  interface_group: production_route
  position: 4
  slide_key: demand_industry_aluminium
- key: industry_aluminium_carbothermalreduction_electricity_share
  share_group: aluminium_production
  step_value: 0.1
  unit: "%"
  interface_group: production_route
  position: 3
  slide_key: demand_industry_aluminium
- key: industry_aluminium_electrolysis_current_electricity_share
  share_group: aluminium_production
  step_value: 0.1
  unit: "%"
  interface_group: production_route
  position: 1
  slide_key: demand_industry_aluminium
