---
- key: industry_useful_demand_for_chemical_fertilizers
  step_value: 0.1
  unit: "%"
  position: 1
  slide_key: demand_industry_chemical_fertilizers
- key: industry_useful_demand_for_chemical_fertilizers_electricity_efficiency
  step_value: 0.1
  unit: "%/year"
  interface_group: efficiency_industry
  position: 20
  slide_key: demand_industry_chemical_fertilizers
- key: industry_useful_demand_for_chemical_fertilizers_useable_heat_efficiency
  step_value: 0.1
  unit: "%/year"
  interface_group: efficiency_industry
  position: 21
  slide_key: demand_industry_chemical_fertilizers
- key: industry_chemicals_fertilizers_burner_network_gas_share
  share_group: chemical_fertilizers_heat
  step_value: 0.1
  unit: "%"
  interface_group: heat production
  related_node: industry_chemicals_fertilizers_burner_network_gas
  position: 50
  slide_key: demand_industry_chemical_fertilizers
- key: industry_chemicals_fertilizers_burner_crude_oil_share
  share_group: chemical_fertilizers_heat
  step_value: 0.1
  unit: "%"
  interface_group: heat production
  related_node: industry_chemicals_fertilizers_burner_crude_oil
  position: 51
  slide_key: demand_industry_chemical_fertilizers
- key: industry_chemicals_fertilizers_burner_coal_share
  share_group: chemical_fertilizers_heat
  step_value: 0.1
  unit: "%"
  interface_group: heat production
  related_node: industry_chemicals_fertilizers_burner_coal
  position: 53
  slide_key: demand_industry_chemical_fertilizers
- key: industry_chemicals_fertilizers_burner_wood_pellets_share
  share_group: chemical_fertilizers_heat
  step_value: 0.1
  unit: "%"
  interface_group: heat production
  related_node: industry_chemicals_fertilizers_burner_wood_pellets
  position: 52
  slide_key: demand_industry_chemical_fertilizers
- key: industry_final_demand_for_chemical_fertilizers_steam_hot_water_share
  share_group: chemical_fertilizers_heat
  step_value: 0.1
  unit: "%"
  interface_group: heat production
  position: 54
  slide_key: demand_industry_chemical_fertilizers
- key: industry_chemicals_fertilizers_steam_methane_reformer_hydrogen_share
  share_group: hydrogen_production
  step_value: 0.1
  unit: "%"
  interface_group: hydrogen_production
  position: 40
  slide_key: demand_industry_chemical_fertilizers
- key: industry_chemicals_fertilizers_hydrogen_network_share
  share_group: hydrogen_production
  step_value: 0.1
  unit: "%"
  interface_group: hydrogen_production
  position: 41
  slide_key: demand_industry_chemical_fertilizers
- key: industry_chemicals_fertilizers_haber_bosch_ammonia_share
  share_group: ammonia_production
  step_value: 0.1
  unit: "%"
  interface_group: ammonia_production
  position: 30
  slide_key: demand_industry_chemical_fertilizers
- key: industry_chemicals_fertilizers_ammonia_network_share
  share_group: ammonia_production
  step_value: 0.1
  unit: "%"
  interface_group: ammonia_production
  position: 31
  slide_key: demand_industry_chemical_fertilizers
- key: industry_chemicals_fertilizers_burner_hydrogen_share
  share_group: chemical_fertilizers_heat
  step_value: 0.1
  unit: "%"
  interface_group: heat production
  related_node: industry_chemicals_fertilizers_burner_hydrogen
  position: 55
  slide_key: demand_industry_chemical_fertilizers
- key: capacity_of_industry_chemicals_fertilizers_flexibility_p2h_electricity
  step_value: 1.0
  unit: MW
  interface_group: hybrid_heating
  related_node: industry_chemicals_fertilizers_flexibility_p2h_network_gas_electricity
  position: 100
  slide_key: demand_industry_chemical_fertilizers
