---
- key: capacity_of_industry_metal_flexibility_load_shifting_electricity
  step_value: 0.1
  unit: "%"
  interface_group: load_shifting_metal
  position: 1
  slide_key: flexibility_flexibility_demand_response_load_shifting
- key: wta_of_industry_metal_flexibility_load_shifing_electricity
  step_value: 0.1
  unit: "€/MWh"
  interface_group: load_shifting_metal
  position: 2
  slide_key: flexibility_flexibility_demand_response_load_shifting
- key: deficit_capacity_of_industry_metal_flexibility_load_shifting_electricity
  step_value: 0.1
  unit: "hours"
  interface_group: load_shifting_metal
  position: 3
  slide_key: flexibility_flexibility_demand_response_load_shifting
- key: capacity_of_industry_chemical_flexibility_load_shifting_electricity
  step_value: 0.1
  unit: "%"
  interface_group: load_shifting_chemical
  position: 10
  slide_key: flexibility_flexibility_demand_response_load_shifting
- key: wta_of_industry_chemical_flexibility_load_shifing_electricity
  step_value: 0.1
  unit: "€/MWh"
  interface_group: load_shifting_chemical
  position: 11
  slide_key: flexibility_flexibility_demand_response_load_shifting
- key: deficit_capacity_of_industry_chemical_flexibility_load_shifting_electricity
  step_value: 0.1
  unit: "hours"
  interface_group: load_shifting_chemical
  position: 12
  slide_key: flexibility_flexibility_demand_response_load_shifting
- key: capacity_of_industry_other_flexibility_load_shifting_electricity
  step_value: 0.1
  unit: "%"
  interface_group: load_shifting_other
  position: 20
  slide_key: flexibility_flexibility_demand_response_load_shifting
- key: wta_of_industry_other_flexibility_load_shifing_electricity
  step_value: 0.1
  unit: "€/MWh"
  interface_group: load_shifting_other
  position: 21
  slide_key: flexibility_flexibility_demand_response_load_shifting
- key: deficit_capacity_of_industry_other_flexibility_load_shifting_electricity
  step_value: 0.1
  unit: "hours"
  interface_group: load_shifting_other
  position: 22
  slide_key: flexibility_flexibility_demand_response_load_shifting
