api_url: https://engine.energytransitionmodel.com
converter_detail_url: https://engine.energytransitionmodel.com/converters
esdl_api_url: https://esdl.energytransitionmodel.com/api/v1/
gquery_detail_url: https://engine.energytransitionmodel.com/data/latest/gqueries/
live_server: staging
multi_year_charts_url: https://energytransitionmodel.com
partners_url: https://energytransitionmodel.com
