# WARNING: If you change this, the current 'vcr' cassettes (s. spec/cassettes/) will not be found -
#          have to be manually adapted (s. spec_helper.rb -> default_cassette_options -> :record) or re-recorded
api_url: https://beta-engine.energytransitionmodel.com

incoming_webhook_keys:
  mailchimp: abc
